### ISSUE TITLE
Query documents inside a Subcollection

### ISSUE THREAD

**Issue by lyamone** [ngxs-labs/firestore-plugin#22] opened 2020-12-28 15:47 UTC
Hi guys, 

First of all, I would like to thank you because the library is great but I am struggling to query a subcollection. 

I have the following service which extends the Ngxs Firestore Class and where I set the path to the parent collection:

`import { Injectable } from '@angular/core';
import { Course } from '@course/course.model';
import { NgxsFirestore } from '@ngxs-labs/firestore-plugin';
@Injectable()
export class CourseService extends NgxsFirestore<Course>  {
  protected path = 'course';
}
`
The problem comes when I want to query all the documents within a Subscribers subcollection. 
The path looks like this: `course/courseId/subscriptions`

I tried to change the path with a dynamic one without luck.

In the [Angular Fire documentation](https://github.com/angular/angularfire/blob/master/docs/firestore/documents.md#retrieving-nested-collections) is possible to query subcollection because we can get the reference: 

`constructor(private afs: AngularFirestore) {
    this.userDoc = afs.doc<Item>('user/david');
    this.tasks = this.userDoc.collection<Task>('tasks').valueChanges();
  }`

Is there a way that I am missing to get subcollections? or It's a feature not supported yet in the library?

Thanks!!

**Comment by joaqcid** [comment] 2020-12-30 15:10
Duplicate of #21

**Closed by joaqcid** 2020-12-30 15:10 UTC
